### ISSUE TITLE
私有pod库lint不过

### ISSUE THREAD

**Issue by zramals** [wuqiuhao/AwsomeReactNative#1]
你好，我这边也想用同样的方式做一个私有的RN pod库，但是按照你的spec同样编写，lint不过，请问你这边是怎么处理的，还请不吝赐教~

**Comment by wuqiuhao** [comment]
你好🤝，我是参考的这篇文章中的解决方案。https://www.jianshu.com/p/88180b4d2ab7 <https://www.jianshu.com/p/88180b4d2ab7>

**Comment by zramals** [comment]
好的 感谢~
